# 通过参数配置文件
# name: application-yml-tony
# 可以使用随机值
name: ${random.value}
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        # 开放所有端点
        include: "*"
  endpoint:
    health:
      show-details: always
  server:
    port: 8081

com:
  study:
    username: 123